### ISSUE TITLE
邮件乱码

### ISSUE THREAD

**Issue by U29kaXVt** [osuuu/LightPicture#3]
如图：
![pic](https://s4.ax1x.com/2022/02/27/bmcetP.jpg)

**Comment by osuuu** [comment]
已更新，请进入后台进行在线更新

**Comment by U29kaXVt** [comment]
> 已更新，请进入后台进行在线更新

好的，顺便问一下，腾讯云cos的问题修复了吗

**Comment by U29kaXVt** [comment]
好的好的，刚刚看到更新日志有个腾讯云cos的修复，谢谢作者大大
